stages:
  - build
  - publish
  
variables:
  DEBIAN_FRONTEND: noninteractive
  VERSION: 0.6

build-bookworm:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: debian-package-builder-bookworm:v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-bookworm:
  stage: publish
  needs:
    - build-bookworm
  dependencies:
    - build-bookworm
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/bookworm/pcapmirror_$VERSION-deb12_amd64.deb'

build-trixie:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: debian-package-builder-trixie:v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-trixie:
  stage: publish
  needs:
    - build-trixie
  dependencies:
    - build-trixie
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/trixie/pcapmirror_$VERSION-deb13_amd64.deb'

build-sid:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: debian-package-builder-sid:v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-sid:
  stage: publish
  needs:
    - build-sid
  dependencies:
    - build-sid
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/sid/pcapmirror_$VERSION-sid_amd64.deb'

build-rocky9:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: rockylinux-package-builder-9:v1
  script:
    - dnf install -y libpcap-devel
    - mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - tar -czf /root/rpmbuild/SOURCES/pcapmirror-v${VERSION}.tar.gz --exclude=debian --exclude=.git .
    - cp -r * /root/rpmbuild/BUILD
    - rpmbuild -ba pcapmirror.spec
    - mkdir -p build
    - mv /root/rpmbuild/RPMS/x86_64/pcapmirror*.* build/
    - mv /root/rpmbuild/SRPMS/pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-rocky9:
  stage: publish
  needs:
    - build-rocky9
  dependencies:
    - build-rocky9
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror-$VERSION-*.el9.x86_64.rpm ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/rockylinux9/pcapmirror-$VERSION-1.el8.x86_64.rpm'

build-rocky8:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: rockylinux-package-builder-8:v1
  script:
    - dnf install -y libpcap-devel
    - mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - tar -czf /root/rpmbuild/SOURCES/pcapmirror-v${VERSION}.tar.gz --exclude=debian --exclude=.git .
    - cp -r * /root/rpmbuild/BUILD
    - rpmbuild -ba pcapmirror.spec
    - mkdir -p build
    - mv /root/rpmbuild/RPMS/x86_64/pcapmirror*.* build/
    - mv /root/rpmbuild/SRPMS/pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-rocky8:
  stage: publish
  needs:
    - build-rocky8
  dependencies:
    - build-rocky8
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror-$VERSION-*.el8.x86_64.rpm ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/rockylinux8/pcapmirror-$VERSION-1.el8.x86_64.rpm'

build-pios12:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic
  image: pios-package-builder-bookworm:v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-pios12:
  stage: publish
  needs:
    - build-pios12
  dependencies:
    - build-pios12
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_armhf.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/bookworm/pcapmirror_$VERSION-piso12_armhf.deb'

build-pios12-64:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic
  image: pios-package-builder-bookworm:64-v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-pios12-64:
  stage: publish
  needs:
    - build-pios12-64
  dependencies:
    - build-pios12-64
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_arm64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/bookworm/pcapmirror_$VERSION-pios12_arm64.deb'

build-plucky:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: ubuntu-package-builder-plucky:v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-plucky:
  stage: publish
  needs:
    - build-plucky
  dependencies:
    - build-plucky
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/trixie/pcapmirror_$VERSION-ubu25.04_amd64.deb'

build-noble:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - docker-generic 
  image: ubuntu-package-builder-noble:v1
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-noble:
  stage: publish
  needs:
    - build-noble
  dependencies:
    - build-noble
  only:
    - tags
  tags:
    - docker-generic
  image: debian-package-builder-bookworm:v1
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/trixie/pcapmirror_$VERSION-ubu24.04_amd64.deb'

# build-linuxstatic:
#   stage: build
#   needs: []
#   only:
#     - tags
#   tags:
#     - docker-generic 
#   image: debian-package-builder-bookworm:v1
#   script:
#     - apt-get update && apt-get install -y libpcap-dev libsystemd-dev libpcap0.8-dev
#     - make static
#     - mkdir -p build
#     - tar -czf build/pcapmirror_amd64.tgz pcapmirror pcapmirror.8.gz README.md
#   artifacts:
#     paths:
#       - build

# publish-linuxstatic:
#   stage: publish
#   needs:
#     - build-bookworm
#   dependencies:
#     - build-bookworm
#   only:
#     - tags
#   tags:
#     - docker-generic
#   image: debian-package-builder-bookworm:v1
#   script:
#     - apt-get update && apt-get install -y curl
#     - ls -la build
#     - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_amd64.tgz ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/linux_static/pcapmirror_$VERSION_amd64.tgz'

