
stages:
  - build
  - publish
  
variables:
  DEBIAN_FRONTEND: noninteractive
  VERSION: 0.6

build-bookworm:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - bookworm
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-bookworm:
  stage: publish
  needs:
    - build-bookworm
  dependencies:
    - build-bookworm
  only:
    - tags
  tags:
    - bookworm
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/bookworm/pcapmirror_$VERSION-1_amd64.deb'

build-sid:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - sid
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-sid:
  stage: publish
  needs:
    - build-sid
  dependencies:
    - build-sid
  only:
    - tags
  tags:
    - bookworm
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_amd64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/sid/pcapmirror_$VERSION-1_amd64.deb'

build-rocky9:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - rocky9
  script:
    - dnf install -y libpcap-devel
    - mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - tar -czf /root/rpmbuild/SOURCES/pcapmirror-v${VERSION}.tar.gz --exclude=debian --exclude=.git .
    - cp -r * /root/rpmbuild/BUILD
    - rpmbuild -ba pcapmirror.spec
    - mkdir -p build
    - mv /root/rpmbuild/RPMS/x86_64/pcapmirror*.* build/
    - mv /root/rpmbuild/SRPMS/pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-rocky9:
  stage: publish
  needs:
    - build-rocky9
  dependencies:
    - build-rocky9
  only:
    - tags
  tags:
    - bookworm
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror-$VERSION-*.el9.x86_64.rpm ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/rockylinux9/pcapmirror-$VERSION-1.el8.x86_64.rpm'

build-rocky8:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - rocky8
  script:
    - dnf install -y libpcap-devel
    - mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - tar -czf /root/rpmbuild/SOURCES/pcapmirror-v${VERSION}.tar.gz --exclude=debian --exclude=.git .
    - cp -r * /root/rpmbuild/BUILD
    - rpmbuild -ba pcapmirror.spec
    - mkdir -p build
    - mv /root/rpmbuild/RPMS/x86_64/pcapmirror*.* build/
    - mv /root/rpmbuild/SRPMS/pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-rocky8:
  stage: publish
  needs:
    - build-rocky8
  dependencies:
    - build-rocky8
  only:
    - tags
  tags:
    - bookworm
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror-$VERSION-*.el8.x86_64.rpm ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/rockylinux8/pcapmirror-$VERSION-1.el8.x86_64.rpm'

build-pios12:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - pios12
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-pios12:
  stage: publish
  needs:
    - build-pios12
  dependencies:
    - build-pios12
  only:
    - tags
  tags:
    - bookworm
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_armhf.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/bookworm/pcapmirror_$VERSION-1_armhf.deb'

build-pios12-64:
  stage: build
  needs: []
  only:
    - tags
  tags:
    - pios12-64
  script:
    - tar -czf ../pcapmirror_$VERSION.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build

publish-pios12-64:
  stage: publish
  needs:
    - build-pios12-64
  dependencies:
    - build-pios12-64
  only:
    - tags
  tags:
    - bookworm
  script:
    - apt-get update && apt-get install -y curl
    - ls -la build
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/pcapmirror_$VERSION-1_arm64.deb ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pcapmirror/bookworm/pcapmirror_$VERSION-1_arm64.deb'
