
stages:
  - build
  
variables:
  DEBIAN_FRONTEND: noninteractive

build-bookworm:
  stage: build
  tags:
    - bookworm
  script:
    - tar -czf ../pcapmirror_0.2.orig.tar.gz --exclude=debian .
    - apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build/*.deb
      - build/*.dsc
      - build/*.tar.xz
      - build/*.changes
      - build/*.buildinfo
      - build/*.diff.gz
