
stages:
  - build
  
variables:
  DEBIAN_FRONTEND: noninteractive

build-bookworm:
  stage: build
  tags:
    - bookworm
  script:
    - debuild -us -uc
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build/*.deb
      - build/*.dsc
      - build/*.tar.xz
      - build/*.changes
      - build/*.buildinfo
      - build/*.diff.gz
