
stages:
  - build-bookworm
  
variables:
  DEBIAN_FRONTEND: noninteractive

build-bookworm:
  stage: build
  tags:
    - bookworm
  script:
    - mkdir -p build
    - cp -r * build/
    - cd build
    - debuild -us -uc
  artifacts:
    paths:
      - build/*.deb
      - build/*.dsc
      - build/*.tar.xz
      - build/*.changes
      - build/*.buildinfo
      - build/*.diff.gz
