
stages:
  - build
  
variables:
  DEBIAN_FRONTEND: noninteractive

build-bookworm:
  stage: build
  only:
    - tags
  tags:
    - bookworm
  script:
    - tar -czf ../pcapmirror_0.2.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build/*.deb
      - build/*.dsc
      - build/*.tar.xz
      - build/*.tar.gz
      - build/*.changes
      - build/*.buildinfo
      - build/*.diff.gz

build-sid:
  stage: build
  only:
    - tags
  tags:
    - sid
  script:
    - tar -czf ../pcapmirror_0.2.orig.tar.gz --exclude=debian .
    - apt-get update && apt-get install -y libpcap-dev
    - dpkg-buildpackage -uc -us
    - mkdir -p build
    - mv ../pcapmirror*.* build/

  artifacts:
    paths:
      - build/*.deb
      - build/*.dsc
      - build/*.tar.xz
      - build/*.tar.gz
      - build/*.changes
      - build/*.buildinfo
      - build/*.diff.gz

build-rocky9:
  stage: build
  tags:
    - rocky9
  script:
    - dnf install -y libpcap-devel
    - mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - cp -r * /root/rpmbuild/BUILD
    - rpmbuild -ba pcapmirror.spec
    - mkdir -p build
    - mv /root/rpmbuild/RPMS/x86_64/pcapmirror*.* build/
    - mv /root/rpmbuild/SRPMS/pcapmirror*.* build/
    - mv /root/rpmbuild/SPECS/pcapmirror*.* build/
    - mv /root/rpmbuild/BUILD/pcapmirror*.* build/

  artifacts:
    paths:
      - build/*
